import type { Location, TransportMode } from "./types";

export const LOCATIONS: readonly Location[] = [
  {
    id: "rome",
    name: "Roma",
    aliases: ["Rome"],
    country: "IT",
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: "Europe/Rome",
    airportCode: "FCO",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Roma (FCO)",
      train: "Roma Termini",
      bus: "Roma Tiburtina",
      ferry: "Civitavecchia",
    },
  },
  {
    id: "milan",
    name: "Milano",
    aliases: ["Milan"],
    country: "IT",
    latitude: 45.4642,
    longitude: 9.19,
    timezone: "Europe/Rome",
    airportCode: "MXP",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: {
      flight: "Milano (MXP)",
      train: "Milano Centrale",
      bus: "Milano Lampugnano",
    },
  },
  {
    id: "naples",
    name: "Napoli",
    aliases: ["Naples"],
    country: "IT",
    latitude: 40.8518,
    longitude: 14.2681,
    timezone: "Europe/Rome",
    airportCode: "NAP",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Napoli (NAP)",
      train: "Napoli Centrale",
      ferry: "Napoli Porto",
    },
  },
  {
    id: "turin",
    name: "Torino",
    aliases: ["Turin"],
    country: "IT",
    latitude: 45.0703,
    longitude: 7.6869,
    timezone: "Europe/Rome",
    airportCode: "TRN",
    hubRank: 1,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Torino (TRN)", train: "Torino Porta Susa" },
  },
  {
    id: "florence",
    name: "Firenze",
    aliases: ["Florence"],
    country: "IT",
    latitude: 43.7696,
    longitude: 11.2558,
    timezone: "Europe/Rome",
    airportCode: "FLR",
    hubRank: 1,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Firenze (FLR)", train: "Firenze S. M. Novella" },
  },
  {
    id: "venice",
    name: "Venezia",
    aliases: ["Venice"],
    country: "IT",
    latitude: 45.4408,
    longitude: 12.3155,
    timezone: "Europe/Rome",
    airportCode: "VCE",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Venezia (VCE)",
      train: "Venezia S. Lucia",
      ferry: "Venezia Porto",
    },
  },
  {
    id: "palermo",
    name: "Palermo",
    aliases: [],
    country: "IT",
    latitude: 38.1157,
    longitude: 13.3615,
    timezone: "Europe/Rome",
    airportCode: "PMO",
    hubRank: 1,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Palermo (PMO)",
      train: "Palermo Centrale",
      ferry: "Palermo Porto",
    },
  },
  {
    id: "bologna",
    name: "Bologna",
    aliases: [],
    country: "IT",
    latitude: 44.4949,
    longitude: 11.3426,
    timezone: "Europe/Rome",
    airportCode: "BLQ",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Bologna (BLQ)", train: "Bologna Centrale" },
  },
  {
    id: "dubai",
    name: "Dubai",
    aliases: [],
    country: "AE",
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: "Asia/Dubai",
    airportCode: "DXB",
    hubRank: 3,
    modes: ["flight", "bus"],
    terminals: { flight: "Dubai (DXB)" },
  },
  {
    id: "tokyo",
    name: "Tokyo",
    aliases: [],
    country: "JP",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    airportCode: "HND",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Tokyo (HND)", train: "Tokyo Station" },
  },
  {
    id: "new-york",
    name: "New York",
    aliases: ["New York City", "NYC"],
    country: "US",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    airportCode: "JFK",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "New York (JFK)", train: "New York Penn Station" },
  },
  {
    id: "bangkok",
    name: "Bangkok",
    aliases: [],
    country: "TH",
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: "Asia/Bangkok",
    airportCode: "BKK",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Bangkok (BKK)", train: "Bangkok Krung Thep Aphiwat" },
  },
  {
    id: "barcelona",
    name: "Barcellona",
    aliases: ["Barcelona"],
    country: "ES",
    latitude: 41.3874,
    longitude: 2.1686,
    timezone: "Europe/Madrid",
    airportCode: "BCN",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Barcellona (BCN)",
      train: "Barcelona Sants",
      ferry: "Barcelona Porto",
    },
  },
  {
    id: "amsterdam",
    name: "Amsterdam",
    aliases: [],
    country: "NL",
    latitude: 52.3676,
    longitude: 4.9041,
    timezone: "Europe/Amsterdam",
    airportCode: "AMS",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Amsterdam (AMS)", train: "Amsterdam Centraal" },
  },
  {
    id: "london",
    name: "Londra",
    aliases: ["London"],
    country: "GB",
    latitude: 51.5072,
    longitude: -0.1276,
    timezone: "Europe/London",
    airportCode: "LHR",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Londra (LHR)", train: "London St Pancras" },
  },
  {
    id: "paris",
    name: "Parigi",
    aliases: ["Paris"],
    country: "FR",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    airportCode: "CDG",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Parigi (CDG)", train: "Paris Gare du Nord" },
  },
  {
    id: "madrid",
    name: "Madrid",
    aliases: [],
    country: "ES",
    latitude: 40.4168,
    longitude: -3.7038,
    timezone: "Europe/Madrid",
    airportCode: "MAD",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Madrid (MAD)", train: "Madrid Atocha" },
  },
  {
    id: "lisbon",
    name: "Lisbona",
    aliases: ["Lisbon", "Lisboa"],
    country: "PT",
    latitude: 38.7223,
    longitude: -9.1393,
    timezone: "Europe/Lisbon",
    airportCode: "LIS",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Lisbona (LIS)",
      train: "Lisboa Oriente",
      ferry: "Lisbona Porto",
    },
  },
  {
    id: "brussels",
    name: "Bruxelles",
    aliases: ["Brussels"],
    country: "BE",
    latitude: 50.8503,
    longitude: 4.3517,
    timezone: "Europe/Brussels",
    airportCode: "BRU",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Bruxelles (BRU)", train: "Bruxelles-Midi" },
  },
  {
    id: "zurich",
    name: "Zurigo",
    aliases: ["Zurich", "Zürich"],
    country: "CH",
    latitude: 47.3769,
    longitude: 8.5417,
    timezone: "Europe/Zurich",
    airportCode: "ZRH",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Zurigo (ZRH)", train: "Zürich HB" },
  },
  {
    id: "munich",
    name: "Monaco di Baviera",
    aliases: ["Monaco", "Munich", "München"],
    country: "DE",
    latitude: 48.1351,
    longitude: 11.582,
    timezone: "Europe/Berlin",
    airportCode: "MUC",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Monaco di Baviera (MUC)", train: "München Hbf" },
  },
  {
    id: "frankfurt",
    name: "Francoforte",
    aliases: ["Frankfurt", "Frankfurt am Main"],
    country: "DE",
    latitude: 50.1109,
    longitude: 8.6821,
    timezone: "Europe/Berlin",
    airportCode: "FRA",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Francoforte (FRA)", train: "Frankfurt Hbf" },
  },
  {
    id: "berlin",
    name: "Berlino",
    aliases: ["Berlin"],
    country: "DE",
    latitude: 52.52,
    longitude: 13.405,
    timezone: "Europe/Berlin",
    airportCode: "BER",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Berlino (BER)", train: "Berlin Hbf" },
  },
  {
    id: "vienna",
    name: "Vienna",
    aliases: ["Wien"],
    country: "AT",
    latitude: 48.2082,
    longitude: 16.3738,
    timezone: "Europe/Vienna",
    airportCode: "VIE",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Vienna (VIE)", train: "Wien Hauptbahnhof" },
  },
  {
    id: "prague",
    name: "Praga",
    aliases: ["Prague", "Praha"],
    country: "CZ",
    latitude: 50.0755,
    longitude: 14.4378,
    timezone: "Europe/Prague",
    airportCode: "PRG",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Praga (PRG)", train: "Praha hlavní nádraží" },
  },
  {
    id: "budapest",
    name: "Budapest",
    aliases: [],
    country: "HU",
    latitude: 47.4979,
    longitude: 19.0402,
    timezone: "Europe/Budapest",
    airportCode: "BUD",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Budapest (BUD)", train: "Budapest Keleti" },
  },
  {
    id: "warsaw",
    name: "Varsavia",
    aliases: ["Warsaw", "Warszawa"],
    country: "PL",
    latitude: 52.2297,
    longitude: 21.0122,
    timezone: "Europe/Warsaw",
    airportCode: "WAW",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Varsavia (WAW)", train: "Warszawa Centralna" },
  },
  {
    id: "copenhagen",
    name: "Copenaghen",
    aliases: ["Copenhagen", "København"],
    country: "DK",
    latitude: 55.6761,
    longitude: 12.5683,
    timezone: "Europe/Copenhagen",
    airportCode: "CPH",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Copenaghen (CPH)", train: "København H" },
  },
  {
    id: "stockholm",
    name: "Stoccolma",
    aliases: ["Stockholm"],
    country: "SE",
    latitude: 59.3293,
    longitude: 18.0686,
    timezone: "Europe/Stockholm",
    airportCode: "ARN",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Stoccolma (ARN)", train: "Stockholm Central" },
  },
  {
    id: "oslo",
    name: "Oslo",
    aliases: [],
    country: "NO",
    latitude: 59.9139,
    longitude: 10.7522,
    timezone: "Europe/Oslo",
    airportCode: "OSL",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Oslo (OSL)", train: "Oslo S" },
  },
  {
    id: "ljubljana",
    name: "Lubiana",
    aliases: ["Ljubljana"],
    country: "SI",
    latitude: 46.0569,
    longitude: 14.5058,
    timezone: "Europe/Ljubljana",
    airportCode: "LJU",
    hubRank: 1,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Lubiana (LJU)", train: "Ljubljana Station" },
  },
  {
    id: "zagreb",
    name: "Zagabria",
    aliases: ["Zagreb"],
    country: "HR",
    latitude: 45.815,
    longitude: 15.9819,
    timezone: "Europe/Zagreb",
    airportCode: "ZAG",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Zagabria (ZAG)", train: "Zagreb Glavni kolodvor" },
  },
  {
    id: "belgrade",
    name: "Belgrado",
    aliases: ["Belgrade", "Beograd"],
    country: "RS",
    latitude: 44.7866,
    longitude: 20.4489,
    timezone: "Europe/Belgrade",
    airportCode: "BEG",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Belgrado (BEG)", train: "Beograd Centar" },
  },
  {
    id: "split",
    name: "Spalato",
    aliases: ["Split"],
    country: "HR",
    latitude: 43.5081,
    longitude: 16.4402,
    timezone: "Europe/Zagreb",
    airportCode: "SPU",
    hubRank: 1,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Spalato (SPU)",
      train: "Split Station",
      ferry: "Split Porto",
    },
  },
  {
    id: "athens",
    name: "Atene",
    aliases: ["Athens"],
    country: "GR",
    latitude: 37.9838,
    longitude: 23.7275,
    timezone: "Europe/Athens",
    airportCode: "ATH",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Atene (ATH)",
      train: "Atene Centrale",
      ferry: "Pireo",
    },
  },
  {
    id: "patras",
    name: "Patrasso",
    aliases: ["Patras"],
    country: "GR",
    latitude: 38.2466,
    longitude: 21.7346,
    timezone: "Europe/Athens",
    airportCode: "GPA",
    hubRank: 0,
    modes: ["train", "bus", "ferry"],
    terminals: { train: "Patrasso", ferry: "Patrasso Porto" },
  },
  {
    id: "thessaloniki",
    name: "Salonicco",
    aliases: ["Thessaloniki"],
    country: "GR",
    latitude: 40.6401,
    longitude: 22.9444,
    timezone: "Europe/Athens",
    airportCode: "SKG",
    hubRank: 2,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Salonicco (SKG)", train: "Thessaloniki Station" },
  },
  {
    id: "istanbul",
    name: "Istanbul",
    aliases: ["İstanbul"],
    country: "TR",
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: "Europe/Istanbul",
    airportCode: "IST",
    hubRank: 3,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Istanbul (IST)",
      train: "Istanbul Söğütlüçeşme",
      ferry: "Istanbul Porto",
    },
  },
  {
    id: "doha",
    name: "Doha",
    aliases: [],
    country: "QA",
    latitude: 25.2854,
    longitude: 51.531,
    timezone: "Asia/Qatar",
    airportCode: "DOH",
    hubRank: 3,
    modes: ["flight", "bus"],
    terminals: { flight: "Doha (DOH)" },
  },
  {
    id: "cairo",
    name: "Il Cairo",
    aliases: ["Cairo"],
    country: "EG",
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: "Africa/Cairo",
    airportCode: "CAI",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Il Cairo (CAI)", train: "Cairo Ramses" },
  },
  {
    id: "casablanca",
    name: "Casablanca",
    aliases: [],
    country: "MA",
    latitude: 33.5731,
    longitude: -7.5898,
    timezone: "Africa/Casablanca",
    airportCode: "CMN",
    hubRank: 2,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Casablanca (CMN)", train: "Casa Voyageurs" },
  },
  {
    id: "reykjavik",
    name: "Reykjavik",
    aliases: ["Reykjavík"],
    country: "IS",
    latitude: 64.1466,
    longitude: -21.9426,
    timezone: "Atlantic/Reykjavik",
    airportCode: "KEF",
    hubRank: 2,
    modes: ["flight", "bus"],
    terminals: { flight: "Reykjavik (KEF)" },
  },
  {
    id: "singapore",
    name: "Singapore",
    aliases: [],
    country: "SG",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    airportCode: "SIN",
    hubRank: 3,
    modes: ["flight", "bus", "ferry"],
    terminals: { flight: "Singapore (SIN)" },
  },
  {
    id: "delhi",
    name: "Delhi",
    aliases: ["New Delhi"],
    country: "IN",
    latitude: 28.6139,
    longitude: 77.209,
    timezone: "Asia/Kolkata",
    airportCode: "DEL",
    hubRank: 3,
    modes: ["flight", "train", "bus"],
    terminals: { flight: "Delhi (DEL)", train: "New Delhi Station" },
  },
  {
    id: "bari",
    name: "Bari",
    aliases: [],
    country: "IT",
    latitude: 41.1171,
    longitude: 16.8719,
    timezone: "Europe/Rome",
    airportCode: "BRI",
    hubRank: 1,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: { flight: "Bari (BRI)", train: "Bari Centrale", ferry: "Bari" },
  },
  {
    id: "brindisi",
    name: "Brindisi",
    aliases: [],
    country: "IT",
    latitude: 40.6327,
    longitude: 17.9418,
    timezone: "Europe/Rome",
    airportCode: "BDS",
    hubRank: 1,
    modes: ["flight", "train", "bus", "ferry"],
    terminals: {
      flight: "Brindisi (BDS)",
      train: "Brindisi",
      ferry: "Brindisi",
    },
  },
];

export const LOCATION_BY_ID = new Map(
  LOCATIONS.map((location) => [location.id, location]),
);

const normalizeName = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLocaleLowerCase("it");

const LOCATION_BY_NAME = new Map<string, Location>();
for (const location of LOCATIONS) {
  for (const candidate of [location.id, location.name, ...location.aliases]) {
    LOCATION_BY_NAME.set(normalizeName(candidate), location);
  }
}

export const SEARCH_LOCATION_NAMES = LOCATIONS.map((location) => location.name);

export function resolveLocation(value: string): Location | undefined {
  return LOCATION_BY_NAME.get(normalizeName(value));
}

export function terminalName(location: Location, mode: TransportMode): string {
  return (
    location.terminals?.[mode] ??
    (mode === "flight" && location.airportCode
      ? `${location.name} (${location.airportCode})`
      : location.name)
  );
}
